title : "Village Fire 2015"

baseurl: "http://villagefiresinging.com"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

include: [".htaccess"]
